
#ifndef __LEARNING_GEM5_HELLO_OBJECT_HH__
#define __LEARNING_GEM5__HELLO_OBJECT_HH__

//
//

#include "params/HelloObject2.hh"
#include "sim/sim_object.hh"

class HelloObject2: public SimObject
{
  public:
    // The constructor of all SimObject assumes it will take a parameter
    // object. This parameter object is automatically created by the build
    // system. The parameter object is based on the python class for the
    // SimObject. The name is autogenerated based on python class name, i.e.
    // HelloObject*Params*
    HelloObject2(HelloObject2Params *p);
};




#endif // __LEARNING_GEM5_HELLO_OBJECT_HH__
